export const themes = [
    { name: 'Light', value: 'light', colors: { text: '#000000', background: '#ffffff' } },
    { name: 'Dark', value: 'dark', colors: { text: '#ffffff', background: '#000000' } },
    { name: 'Circuit', value: 'circuit', colors: { text: '#e2d067', background: '#29292b' } },
    { name: 'Deepsea', value: 'deepsea', colors: { text: '#e9ecef', background: '#101c29' } },
    { name: 'Violet', value: 'violet', colors: { text: '#f4daf9', background: '#403a49' } },
    { name: 'Volcano', value: 'volcano', colors: { text: '#ffcbcb', background: '#491b18' } },
    { name: 'Forest', value: 'forest', colors: { text: '#ddfade', background: '#454527' } },
    { name: 'Celestial', value: 'celestial', colors: { text: '#092328', background: '#caf0f8' } },
    { name: 'Solarized', value: 'solarized', colors: { text: '#f5e9d3', background: '#f27059' } },
    { name: 'Barbie', value: 'barbie', colors: { text: '#ffe5ec', background: '#fb6f92' } },
    { name: 'Candy', value: 'candy', colors: { text: '#8e7dbe', background: '#ffcfd2' } },
    { name: 'Aurora', value: 'aurora', colors: { text: '#7dfaca', background: '#382940' } },
    { name: 'Cyberpunk', value: 'cyberpunk', colors: { text: '#f7eb6a', background: '#ba3475' } },
    { name: 'Hacker', value: 'hacker', colors: { text: '#68e372', background: '#3c3c3b' } },
    { name: 'Neon', value: 'neon', colors: { text: '#ff0073', background: '#390ca3' } },
    { name: 'Cream', value: 'cream', colors: { text: '#22223b', background: '#f2e9e4' } },
    { name: 'Bloodmoon', value: 'bloodmoon', colors: { text: '#ffb3cc', background: '#130007' } },
    { name: 'Dirty', value: 'dirty', colors: { text: '#b88b77', background: '#2f0e07' } },
    { name: 'Pastel', value: 'pastel', colors: { text: '#413b4f', background: '#bf9fc7' } },
    { name: 'Ocean', value: 'ocean', colors: { text: '#001833', background: '#5eafff' } },
    { name: 'Gunmetal', value: 'gunmetal', colors: { text: '#EAE0D5', background: '#22333B' } },
    { name: 'Grape', value: 'grape', colors: { text: '#B76D68', background: '#2c2b3c' } },
    { name: 'Amethyst', value: 'amethyst', colors: { text: '#E2CFEA', background: '#9933ff' } },
    { name: 'Dreamwood', value: 'dreamwood', colors: { text: '#EACDC2', background: '#1a1423' } },
    { name: 'Bloodstain', value: 'bloodstain', colors: { text: '#e33434', background: '#2b2b2b' } },
    { name: 'Military', value: 'military', colors: { text: '#DCD7C9', background: '#2C3639' } },
    { name: 'Mirage', value: 'mirage', colors: { text: '#124f63', background: '#FFCF9D' } },
    { name: 'Electric', value: 'electric', colors: { text: '#00adff', background: '#1B262C' } },
    { name: 'Twilight', value: 'twilight', colors: { text: '#032b21', background: '#71c9c0' } },
    { name: 'Lavender', value: 'lavender', colors: { text: '#DBD8E3', background: '#2A2438' } },
    { name: 'Outer Space', value: 'outer-space', colors: { text: '#d4d4d4', background: '#4c5b61' } },
    { name: 'Abyss', value: 'abyss', colors: { text: '#DFF3E4', background: '#171738' } },
    { name: 'Eggplant', value: 'eggplant', colors: { text: '#fad4e0', background: '#4d2632' } },
    { name: 'Contrast', value: 'contrast', colors: { text: '#ffffff', background: '#000000' } },
    { name: 'Ebony', value: 'ebony', colors: { text: '#e0dbd7', background: '#605856' } },
    { name: 'Scarlet Snow', value: 'scarlet-snow', colors: { text: '#8C271E', background: '#ded8d8' } },
    { name: 'Cinder', value: 'cinder', colors: { text: '#F7FFF7', background: '#343434' } },
    { name: 'Astral', value: 'astral', colors: { text: '#ffe6c4', background: '##2e294d' } },
    { name: 'Anthracite', value: 'anthracite', colors: { text: '#C1BDB3', background: '#323031' } },
    { name: 'Indigo', value: 'indigo', colors: { text: '#D9D9D9', background: '#284B63' } },
    { name: 'Oak', value: 'oak', colors: { text: '#edd7b9', background: '#534D41' } },
    { name: 'Eclipse', value: 'eclipse', colors: { text: '#EEC643', background: '#011638' } },
    { name: 'Cake', value: 'cake', colors: { text: '#F9DBBD', background: '#450920' } },
    { name: 'Evernight', value: 'evernight', colors: { text: '#CAD2C5', background: '#2F3E460' } },
    { name: 'Duskwood', value: 'duskwood', colors: { text: '#e3ddf0', background: '#3D2C2E' } },
  ];
