export const themes = [
    { name: 'Light', value: 'light', colors: { text: '#000000', background: '#ffffff' } },
    { name: 'Dark', value: 'dark', colors: { text: '#ffffff', background: '#000000' } },
    { name: 'Circuit', value: 'circuit', colors: { text: '#e2d067', background: '#29292b' } },
    { name: 'Deepsea', value: 'deepsea', colors: { text: '#e9ecef', background: '#101c29' } },
    { name: 'Violet', value: 'violet', colors: { text: '#f4daf9', background: '#403a49' } },
    { name: 'Volcano', value: 'volcano', colors: { text: '#ffcbcb', background: '#491b18' } },
    { name: 'Forest', value: 'forest', colors: { text: '#ddfade', background: '#454527' } },
    { name: 'Celestial', value: 'celestial', colors: { text: '#092328', background: '#caf0f8' } },
    { name: 'Solarized', value: 'solarized', colors: { text: '#f5e9d3', background: '#f27059' } },
    { name: 'Barbie', value: 'barbie', colors: { text: '#ffe5ec', background: '#fb6f92' } },
    { name: 'Candy', value: 'candy', colors: { text: '#8e7dbe', background: '#ffcfd2' } },
    { name: 'Aurora', value: 'aurora', colors: { text: '#7dfaca', background: '#382940' } },
    { name: 'Cyberpunk', value: 'cyberpunk', colors: { text: '#f7eb6a', background: '#ba3475' } },
    { name: 'Hacker', value: 'hacker', colors: { text: '#68e372', background: '#3c3c3b' } },
    { name: 'Neon', value: 'neon', colors: { text: '#ff0073', background: '#390ca3' } },
    { name: 'Cream', value: 'cream', colors: { text: '#22223b', background: '#f2e9e4' } },
    { name: 'Bloodmoon', value: 'bloodmoon', colors: { text: '#ffb3cc', background: '#130007' } },
    { name: 'Dirty', value: 'dirty', colors: { text: '#b88b77', background: '#2f0e07' } },
    { name: 'Pastel', value: 'pastel', colors: { text: '#413b4f', background: '#bf9fc7' } },
    { name: 'Ocean', value: 'ocean', colors: { text: '#001833', background: '#5eafff' } },
    { name: 'Gunmetal', value: 'gunmetal', colors: { text: '#EAE0D5', background: '#22333B' } },
    { name: 'Grape', value: 'grape', colors: { text: '#B76D68', background: '#2c2b3c' } },
    { name: 'Amethyst', value: 'amethyst', colors: { text: '#E2CFEA', background: '#9933ff' } },
  ];
